## Homework 3 for MLF

Yanrong Wu
1801212952
18 Fintech class

## Pre-precessing

In [1]:
from scipy.io import arff
import pandas as pd
import numpy as np

In [2]:
#loading to dataframe
data = arff.loadarff('4year.arff')
df = pd.DataFrame(data[0])

In [3]:
#creating bankruptcy column
df['bankruptcy'] = (df['class']==b'1')
del df['class']
df.columns = ['X{0:02d}'.format(k) for k in range(1,65)] + ['bankruptcy']

In [4]:
df.describe()

X01          X02          X03           X04           X05  \
count  9791.000000  9791.000000  9791.000000   9749.000000  9.771000e+03   
mean      0.043019     0.596404     0.130959      8.136600  6.465164e+01   
std       0.359321     4.587122     4.559074    290.647281  1.475939e+04   
min     -12.458000     0.000000  -445.910000     -0.045319 -3.794600e+05   
25%       0.001321     0.263145     0.020377      1.047000 -5.121700e+01   
50%       0.041364     0.467740     0.199290      1.591800 -5.557600e-02   
75%       0.111130     0.689255     0.410670      2.880400  5.573200e+01   
max      20.482000   446.910000    22.769000  27146.000000  1.034100e+06   

               X06          X07           X08          X09          X10  ...  \
count  9791.000000  9791.000000   9773.000000  9792.000000  9791.000000  ...   
mean     -0.059273     0.059446     19.884016     1.882296     0.389040  ...   
std       6.812754     0.533344    698.697015    17.674650     4.590299  ...   
min    -486.820000   -12.458000     -1.848200    -0.032371  -445.910000  ...   
25%      -0.000578     0.003004      0.428300     1.006675     0.294440  ...   
50%       0.000000     0.048820      1.088700     1.161300     0.510450  ...   
75%       0.065322     0.126940      2.691000     1.970225     0.714290  ...   
max     322.200000    38.618000  53209.000000  1704.800000    12.602000  ...   

                X55          X56          X57          X58          X59  \
count  9.792000e+03  9771.000000  9791.000000  9776.000000  9791.000000   
mean   7.686330e+03    -0.992263     0.035022     1.133287     0.856053   
std    7.605261e+04    77.007971     8.945365     8.038201    26.393305   
min   -7.132200e+05 -7522.100000  -597.420000   -30.892000  -284.380000   
25%    2.184000e+01     0.003121     0.008768     0.885722     0.000000   
50%    9.503300e+02     0.043679     0.098026     0.958305     0.002129   
75%    4.694550e+03     0.117170     0.242680     0.996163     0.211790   
max    6.123700e+06   112.020000   226.760000   668.750000  1661.000000   

                 X60            X61           X62          X63           X64  
count    9178.000000    9760.000000  9.771000e+03  9749.000000   9561.000000  
mean      118.156064      25.194430  2.015157e+03     8.660813     35.949619  
std      3230.316692    1099.260821  1.171461e+05    60.838202    483.318623  
min         0.000000     -12.656000 -1.496500e+04    -0.024390     -0.000015  
25%         5.356325       4.267700  4.323400e+01     2.938800      2.012900  
50%         9.482000       6.283550  7.472900e+01     4.848900      4.041600  
75%        19.506000       9.938200  1.233450e+02     8.363800      9.413500  
max    251570.000000  108000.000000  1.077900e+07  5662.400000  21153.000000  

[8 rows x 64 columns]

In [5]:
sum(df.bankruptcy == True)

515

In [6]:
#filling-in na values
from sklearn.impute import SimpleImputer
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
X_imp = imp_mean.fit_transform(df.values)

In [7]:
#training-vs-test split
from sklearn.model_selection import train_test_split

X, y = X_imp[:, :-1], X_imp[:, -1]

X_train, X_test, y_train, y_test =\
    train_test_split(X, y, 
                     test_size=0.3, 
                     random_state=0, 
                     stratify=y)

In [8]:
#standardizatino
from sklearn.preprocessing import StandardScaler

stdsc = StandardScaler()
X_train_std = stdsc.fit_transform(X_train)
X_test_std = stdsc.transform(X_test)

## Extract 3 features using PCA method.

In [9]:
from sklearn.decomposition import PCA
PCA = PCA()
PCA = PCA.fit(X_train_std)
PCA_X_train = PCA.transform(X_train_std)
PCA_X_train
#or use one step: PCA_X_train = PCA.fit_transform(X_train_std)

array([[-2.78667362e-01, -1.28388846e-01, -8.39342513e-01, ...,
        -5.72311276e-06, -4.91243001e-07,  6.66133815e-16],
       [-4.91697017e-01, -3.95497883e-02, -3.79015956e-01, ...,
         8.63105491e-08, -7.01676924e-08, -8.32667268e-17],
       [ 2.53375280e-01, -8.06061792e-03,  5.28572294e-01, ...,
        -2.38249043e-06, -1.45428847e-07, -1.11022302e-16],
       ...,
       [ 6.17598355e-01, -1.52470478e-01, -7.01927206e-01, ...,
        -1.94177572e-06,  7.76773334e-08,  1.04732877e-15],
       [-1.55606581e+00,  2.17757199e-01,  3.17678127e+00, ...,
        -5.00908613e-06, -7.87191852e-07,  4.69119822e-16],
       [ 4.64426743e-01, -9.41212649e-02, -4.60034123e-01, ...,
         4.85117712e-06,  3.07184592e-08, -1.38777878e-16]])

In [10]:
PCA.explained_variance_

array([1.11994034e+01, 5.83874380e+00, 5.19411944e+00, 4.23087992e+00,
       3.42390435e+00, 3.05582599e+00, 2.89650494e+00, 2.40639848e+00,
       1.98345880e+00, 1.75112935e+00, 1.58603094e+00, 1.52146524e+00,
       1.37025443e+00, 1.24122096e+00, 1.19873371e+00, 1.13367446e+00,
       1.05959066e+00, 1.00527344e+00, 1.00276500e+00, 9.99996249e-01,
       9.98164015e-01, 9.63611349e-01, 9.38667351e-01, 8.77951425e-01,
       7.99193954e-01, 7.62586585e-01, 6.67570737e-01, 6.42238369e-01,
       5.21518660e-01, 4.71038329e-01, 4.19057280e-01, 3.84346082e-01,
       3.30072008e-01, 2.01397457e-01, 1.82480024e-01, 1.51766497e-01,
       1.21514504e-01, 1.06714888e-01, 6.79438980e-02, 6.07197160e-02,
       5.34654673e-02, 3.68997728e-02, 2.76603363e-02, 2.62746675e-02,
       2.59667279e-02, 2.24571976e-02, 1.95169451e-02, 1.03031382e-02,
       6.78081564e-03, 4.86195308e-03, 2.68403923e-03, 1.88066779e-03,
       1.37471213e-03, 4.76676660e-04, 3.16976043e-04, 3.03001450e-04,
      

In [11]:
PCA.explained_variance_ratio_

array([1.74965147e-01, 9.12170614e-02, 8.11462753e-02, 6.60978536e-02,
       5.34907000e-02, 4.77403147e-02, 4.52512866e-02, 3.75944904e-02,
       3.09870220e-02, 2.73574041e-02, 2.47781178e-02, 2.37694259e-02,
       2.14071017e-02, 1.93912479e-02, 1.87274814e-02, 1.77110790e-02,
       1.65536886e-02, 1.57051058e-02, 1.56659171e-02, 1.56226617e-02,
       1.55940372e-02, 1.50542306e-02, 1.46645375e-02, 1.37159896e-02,
       1.24855836e-02, 1.19136769e-02, 1.04292709e-02, 1.00335104e-02,
       8.14754016e-03, 7.35890007e-03, 6.54681467e-03, 6.00453134e-03,
       5.15662266e-03, 3.14637614e-03, 2.85083437e-03, 2.37100553e-03,
       1.89838710e-03, 1.66717684e-03, 1.06146851e-03, 9.48607140e-04,
       8.35276042e-04, 5.76474830e-04, 4.32129697e-04, 4.10481782e-04,
       4.05670927e-04, 3.50842516e-04, 3.04907775e-04, 1.60963047e-04,
       1.05934786e-04, 7.59569331e-05, 4.19319942e-05, 2.93811469e-05,
       2.14767430e-05, 7.44698613e-06, 4.95202807e-06, 4.73370690e-06,
      

In [12]:
import numpy as np
import matplotlib.pyplot as plt
plt.bar(range(1,65),PCA.explained_variance_ratio_)
plt.plot(range(1,65),np.cumsum(PCA.explained_variance_ratio_))
plt.xlabel("number of components after dimension reduction")
plt.ylabel("cumulative explained variance ratio")
plt.show()

<Figure size 640x480 with 1 Axes>

## Apply LR / SVM / Decision Tree below

In [13]:
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.decomposition import PCA

In [14]:
#LogisticRegression
pipeline_lr = make_pipeline(StandardScaler(), PCA(n_components=3), LogisticRegression())
pipeline_lr.fit(X_train, y_train)
print('LogisticRegression Accuracy: %.4f' % pipeline_lr.score(X_test,y_test))

LogisticRegression Accuracy: 0.9462


//anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [15]:
#Decision Tree
pipeline_tree = make_pipeline(StandardScaler(), PCA(n_components=3), DecisionTreeClassifier())
pipeline_tree.fit(X_train, y_train)
print('DecisionTree Accuracy: %.4f' % pipeline_tree.score(X_test,y_test))

DecisionTree Accuracy: 0.8996


In [28]:
#SVM
pipeline_svm = make_pipeline(StandardScaler(), PCA(n_components=3), SVC())
pipeline_svm.fit(X_train, y_train)
print('SVM Accuracy: %.4f' % pipeline_svm.score(X_test,y_test))

//anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVM Accuracy: 0.9472


## Use grid search for finding optimal hyperparameters. (PML p199). In the search, apply 10-fold cross-validation.

In [17]:
from sklearn.model_selection import GridSearchCV

In [18]:
#LogisticRegression
parammeters = {'logisticregression__penalty': ('l1', 'l2'),'logisticregression__C':[0.01, 0.1, 1, 10, 100, 1000]}
grid_search_lr = GridSearchCV(estimator = pipeline_lr, param_grid=parammeters, n_jobs=1, verbose=0, scoring='accuracy', cv=10)
grid_search_lr = grid_search_lr.fit(X_train, y_train)
print('LogisticRegression Train Accuracy: %.4f' % grid_search_lr.best_score_)
print(grid_search_lr.best_params_)

best_estimator_lr = grid_search_lr.best_estimator_
print('LogisticRegression Test Accuracy: %.4f' % best_estimator_lr.score(X_test, y_test))

//anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
//anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
//anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
//anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
//anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  

LogisticRegression Train Accuracy: 0.9473
{'logisticregression__C': 0.01, 'logisticregression__penalty': 'l1'}
LogisticRegression Test Accuracy: 0.9462


//anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [19]:
#Decision Tree
parammeters = {'criterion':['gini'],'max_depth':[30,50,60,100],'min_samples_leaf':[2,3,5,10],'min_impurity_decrease':[0.1,0.2,0.5]}
grid_search_tree = GridSearchCV(DecisionTreeClassifier(),param_grid=parammeters,cv=10)
grid_search_tree = grid_search_tree.fit(X_train, y_train)

In [20]:
print('Decision Tree Train Accuracy: %.4f' % grid_search_tree.best_score_)
print(grid_search_tree.best_params_)

best_estimator_tree = grid_search_tree.best_estimator_
print('Decision Tree Test Accuracy: %.4f' % best_estimator_tree.score(X_test, y_test))

Decision Tree Train Accuracy: 0.9475
{'criterion': 'gini', 'max_depth': 30, 'min_impurity_decrease': 0.1, 'min_samples_leaf': 2}
Decision Tree Test Accuracy: 0.9472


In [ ]:
#SVM
param_range = [0.01, 0.1, 1, 10, 100, 1000]
param_grid_svm = [{'svc__C' : param_range,
               'svc__kernel' : ['linear']},
              {'svc__C' :  param_range,
               'svc__kernel':  ['rbf'],
                'svc__gamma' : param_range}]
grid_search_svm = GridSearchCV(estimator = pipeline_svm, param_grid=param_grid_svm, scoring='accuracy', cv=10)
grid_search_svm = grid_search_svm.fit(X_train, y_train)
print('SVM Train Accuracy:%.4f' % grid_search_svm.best_score_)
print(grid_search_svm.best_params_)

best_estimator_svc = grid_search_svm.best_estimator_
print('SVM Test Accuracy: %.4f' % best_estimator_svc.score(X_test, y_test))

P.S.: The computation is too slow to show the results, while the code is right. Please check it.